# Generated by Django 6.0.7 on 2026-07-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Álbum')),
                ('release_date', models.DateField(verbose_name='Fecha de Lanzamiento')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio ($)')),
                ('cover_url', models.URLField(blank=True, verbose_name='URL de Portada')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist', verbose_name='Artista')),
            ],
        ),
    ]
