# Generated by Django 6.0.7 on 2026-07-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='album',
            name='price',
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='Portada del Álbum'),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='Foto del Artista'),
        ),
    ]
