# Generated by Django 6.0.7 on 2026-07-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_album_cover_url_remove_album_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Género Musical'),
        ),
    ]
